name: test

on: [push, pull_request]

jobs:
  runs-on: ${{ matrix.os }}
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        nim-version:
          - '1.0'
          - '1.2'
          - '1.4'
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: nimble tests -Y